### ISSUE TITLE
TypeError: 'Query' object is not callable

### ISSUE THREAD

**Issue by zdenop** [ralsina/pyqt-by-example#1]
Hello,

I tried pyqt-by-example/session2 and I got error message:

c:\session2>main.py
Traceback (most recent call last):
  File "c:\session2\main.py", line 59, in <module>
    main()
  File "c:\session2\main.py", line 52, in main
    window=Main()
  File "c:\session2\main.py", line 27, in **init**
    for task in todo.Task.query().all():
TypeError: 'Query' object is not callable

The same message I got for next sessions...

My use elixir  '0.7.1'.

**Comment by dawidof** [comment]
change to todo.Task.query.all()
